#!/usr/bin/bash

_aquaq_cmp() {
  _script_commands=$(./aquaq -h)

  local cur prev
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "${_script_commands}" -- ${cur}) )
  return 0
}

complete -o nospace -F _aquaq_cmp ./aquaq -h
